name: Build and upload to PyPI

# Build on every branch push, tag push, and pull request change:
on: [push]
# Alternatively, to publish when a (published) GitHub Release is created, use the following:
# on:
   #push:
#   pull_request:
#   release:
#     types:
#       - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        #os: [windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
        #CIBW_ENVIRONMENT: 
            #PATH=$PATH:/home/runner/work/python-ibmdb/python-ibmdb/clidirver/bin:/home/runner/work/python-ibmdb/python-ibmdb/clidirver
            #DYLD_LIBRARY_PATH=/home/runner/work/python-ibmdb/python-ibmdb/clidirver/lib:/usr/local/lib
         #CIBW_ARCHS_WINDOWS: "AMD64 x86"
         CIBW_SKIP: "*-win32"
         #CIBW_ENVIRONMENT: DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/lib/gcc/8
          
         #CIBW_BUILD: cp311-macosx_x86_64
         CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
         #CIBW_SKIP: "*-musllinux_* pp*"
         CIBW_REPAIR_WHEEL_COMMAND_LINUX:
            auditwheel repair
              --exclude libdb2.so.1
              --exclude libDB2xml4c.so.58 
              --exclude libm.so.6
              --exclude libcrypt.so.1
              --exclude libpam.so.0
              --exclude librt.so.1
              --exclude libpthread.so.0
              --exclude libc.so.6
              --exclude libdl.so.2
              --wheel-dir {dest_dir}
              {wheel}
 
          

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: |
          pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

