name: Build and upload to PyPI

# Build on every branch push, tag push, and pull request change:
on:
  workflow_dispatch:
  pull_request:
  #push:
    #branches:
     # - test_wheel
  #tags:
   #   - 'v*
  release:
    types:
      - published

env:
   PACKAGE: ibm_db-3.1.4.16    
  
jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip build
      - name: Build sdist
        run: python -m build --sdist --no-isolation
      - name: untar *.tar.gz file 
        run: |
          echo "cd dist"
          cd dist
          echo "tar -xzvf $PACKAGE.tar.gz "
          tar -xzvf $PACKAGE.tar.gz 
          echo "ls"
          ls
          echo "ls $PACKAGE/"
          ls $PACKAGE/
          echo "rm -rf $PACKAGE/clidriver*"
          rm -rf $PACKAGE/clidriver*
          echo "ls"
          ls
          echo "rm -rf $PACKAGE.tar.gz"
          rm -rf $PACKAGE.tar.gz
          echo "ls"
          ls
          echo " ls $PACKAGE/"
          ls $PACKAGE/
          echo "tar -czvf $PACKAGE.tar.gz $PACKAGE"
          tar -czvf $PACKAGE.tar.gz $PACKAGE
          echo "rm -rf $PACKAGE"
          rm -rf $PACKAGE
          echo "ls"
          ls
      - name: Upload sdist
        uses: actions/upload-artifact@v3
        with:
          path: |
            ./dist/$PACKAGE.tar.gz
            
  upload_pypi:
    needs: [build_sdist]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
     #upload to PyPI on every tag starting with 'v'
    #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    # alternatively, to publish when a GitHub Release is created, use the following rule:
    #if: github.event_name == 'release' && github.event.action == 'published'
    steps:
    - uses: actions/download-artifact@v3
      with:
        # unpacks default artifact into dist/
        #if `name: artifact` is omitted, the action will create extra parent dir
        name: artifact
        path: dist
    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: ${{secrets.TESTPYPI_USER}}
        password: ${{ secrets.TESTPYPI_PASSWORD}}
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: ${{secrets.PYPI_USER}}
        password: ${{ secrets.PYPI_PASSWORD}}
