name: Build and upload to PyPI

# Build on every branch push, tag push, and pull request change:
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - test_wheel
  #tags:
   #   - 'v*
  release:
    types:
      - published
jobs:
   build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip build
      - name: Build sdist
        run: python -m build --sdist --no-isolation
      - name: untar *.tar.gz file 
        run: |
          tar -xzvf ./dist/*.tar.gz .
      - name: remove clidriver directory 
        run: |
          rm -rf ./ibm_db-3.1.4.7/clidriver*
          rm -rf ./dist/ibm_db-3.1.4.7/clidriver*
      - name: create tar file 
        run: tar -czvf ./dist/ibm_db-3.1.4.7.tar.gz 

      - name: Upload sdist
        uses: actions/upload-artifact@v3
        with:
          path: |
            ./dist/*.tar.gz
